import 'package:flutter/material.dart';

List song_type_1 = [
  "Music",
  "Rock",
  "Alternative Rock",
];
List song_type_2 = [
  "Made For You",
  "New Released",
  "Popular",
];
List songs = [
  {
    "img": "assets/images/img_1.jpg",
    "title": "Nevermind",
    "description": "Nevermind is Album of Nirvana",
    "song_count": "13 Songs",
    "date": "about 49min 15s",
    "color": Color(0xFFf69129),
    "song_url": "songs/Smells Like Teen Spirit.mp3",
    "songs": [
      {"title": "Smells Like Teen Spirit", "duration": "4:38"},
      {"title": "In Bloom", "duration": "4:15"},
      {"title": "Come As You Are", "duration": "3:38"},
      {"title": "Breed", "duration": "3:04"},
      {"title": "Lithium", "duration": "4:17"},
      {"title": "Polly", "duration": "2:53"},
      {"title": "Territorial Pissings", "duration": "2:22"},
      {"title": "Drain You", "duration": "3:43"},
      {"title": "Lounge Act", "duration": "2:36"},
      {"title": "Stay Away", "duration": "3:31"},
      {"title": "On Plain", "duration": "3:14"},
      {"title": "Something In The Way", "duration": "3:52"},
      {"title": "Endless, Nameless", "duration": "6:43"},
    ]
  },
  {
    "img": "assets/images/img_2.jpg",
    "title": "Sheila On 7",
    "description": "Sheila On 7 is first Album of Sheila On 7",
    "song_count": "10 songs",
    "date": "about 45min 16s",
    "color": Color(0xFF64849c),
    "song_url": "songs/Lounge Act.mp3",
    "songs": [
      {"title": "Tertatih", "duration": "0:00"},
      {"title": "Kita", "duration": "0:00"},
      {"title": "J.A.P", "duration": "0:00"},
      {"title": "Anugerah Terindah Yang Pernah Kumiliki", "duration": "0:00"},
      {"title": "Pede", "duration": "0:00"},
      {"title": "Dan...", "duration": "0:00"},
      {"title": "Terlintas 2 Kata", "duration": "0:00"},
      {"title": "Berai", "duration": "0:00"},
      {"title": "Bobrok", "duration": "0:00"},
      {"title": "Perhatikan, Rani!", "duration": "0:00"},
    ]
  },
  {
    "img": "assets/images/img_3.jfif",
    "title": "07 Des",
    "description": "07 Des is Album Sheila On 7",
    "song_count": "14 songs",
    "date": "about 54min 57s",
    "color": Color(0xFF58546c),
    "song_url": "songs/Drain You.mp3",
    "songs": [
      {"title": "Tunjukkan Padaku", "duration": "0:00"},
      {"title": "Hingga Ujung Waktu", "duration": "0:00"},
      {"title": "Seberapa Pantas", "duration": "0:00"},
      {"title": "Seandainya", "duration": "0:00"},
      {"title": "Buat Aku Tersenyum", "duration": "0:00"},
      {"title": "Saat Aku Lanjut Usia", "duration": "0:00"},
      {"title": "Mari Bercinta", "duration": "0:00"},
      {"title": "Terimakasih Bijaksana", "duration": "0:00"},
      {"title": "Takkan Pernah Menyesal", "duration": "0:00"},
      {"title": "Tentang Hidup", "duration": "0:00"},
      {"title": "Bapak-Bapak", "duration": "0:00"},
      {"title": "Percayakan Padaku", "duration": "0:00"},
      {"title": "Pria Kesepian", "duration": "0:00"},
      {"title": "Waktu Yang Tepat Untuk Berpisah", "duration": "0:00"},
    ]
  },
  {
    "img": "assets/images/img_4.jfif",
    "title": "Taman Langit",
    "description": "Album Noah new released",
    "song_count": "11 songs",
    "date": "about 43min 1s",
    "color": Color(0xFFbad6ec),
    "song_url": "songs/Breed.mp3",
    "songs": [
      {"title": "Sahabat", "duration": "0:00"},
      {"title": "Aku & Bintang", "duration": "0:00"},
      {"title": "Semua Tentang Kita", "duration": "0:00"},
      {"title": "Dan Hilang", "duration": "0:00"},
      {"title": "Satu Hati", "duration": "0:00"},
      {"title": "Mimpi Yang Sempurna", "duration": "0:00"},
      {"title": "Taman Langit", "duration": "0:00"},
      {"title": "Yang Terdalam", "duration": "0:00"},
      {"title": "Tertinggalkan Waktu", "duration": "0:00"},
      {"title": "Kita Tertawa", "duration": "0:00"},
      {"title": "Topeng", "duration": "0:00"},
    ]
  },
  {
    "img": "assets/images/img_5.jpg",
    "title": "Chill Hits",
    "description": "Kick back to the best new and recent chill tunes.",
    "song_count": "13 songs",
    "date": "about 49min 15s",
    "color": Color(0xFFa4c4d3),
    "song_url": "songs/Territorial Pissings.mp3",
    "songs": [
      {"title": "Smells Like Teen Spirit", "duration": "4:38"},
      {"title": "In Bloom", "duration": "4:15"},
      {"title": "Come As You Are", "duration": "3:38"},
      {"title": "Breed", "duration": "3:04"},
      {"title": "Lithium", "duration": "4:17"},
      {"title": "Polly", "duration": "2:53"},
      {"title": "Territorial Pissings", "duration": "2:22"},
      {"title": "Drain You", "duration": "3:43"},
      {"title": "Lounge Act", "duration": "2:36"},
      {"title": "Stay Away", "duration": "3:31"},
      {"title": "On Plain", "duration": "3:14"},
      {"title": "Something In The Way", "duration": "3:52"},
      {"title": "Endless, Nameless", "duration": "6:43"},
    ]
  },
  {
    "img": "assets/images/img_6.jpg",
    "title": "Dark & Stormy",
    "description": "Beautifully dark, dramatic tracks.",
    "song_count": "10 songs",
    "date": "about 45min 16s",
    "color": Color(0xFF5e4f78),
    "song_url": "songs/Lithium.mp3",
    "songs": [
      {"title": "Tertatih", "duration": "0:00"},
      {"title": "Kita", "duration": "0:00"},
      {"title": "J.A.P", "duration": "0:00"},
      {"title": "Anugerah Terindah Yang Pernah Kumiliki", "duration": "0:00"},
      {"title": "Pede", "duration": "0:00"},
      {"title": "Dan...", "duration": "0:00"},
      {"title": "Terlintas 2 Kata", "duration": "0:00"},
      {"title": "Berai", "duration": "0:00"},
      {"title": "Bobrok", "duration": "0:00"},
      {"title": "Perhatikan, Rani!", "duration": "0:00"},
    ]
  },
  {
    "img": "assets/images/img_7.jpg",
    "title": "Feel Good Piano",
    "description": "Positive piano music",
    "song_count": "14 songs",
    "date": "about 54min 57s",
    "color": Color(0xFFa4c1ad),
    "song_url": "songs/In Bloom.mp3",
    "songs": [
      {"title": "Tunjukkan Padaku", "duration": "0:00"},
      {"title": "Hingga Ujung Waktu", "duration": "0:00"},
      {"title": "Seberapa Pantas", "duration": "0:00"},
      {"title": "Seandainya", "duration": "0:00"},
      {"title": "Buat Aku Tersenyum", "duration": "0:00"},
      {"title": "Saat Aku Lanjut Usia", "duration": "0:00"},
      {"title": "Mari Bercinta", "duration": "0:00"},
      {"title": "Terimakasih Bijaksana", "duration": "0:00"},
      {"title": "Takkan Pernah Menyesal", "duration": "0:00"},
      {"title": "Tentang Hidup", "duration": "0:00"},
      {"title": "Bapak-Bapak", "duration": "0:00"},
      {"title": "Percayakan Padaku", "duration": "0:00"},
      {"title": "Pria Kesepian", "duration": "0:00"},
      {"title": "Waktu Yang Tepat Untuk Berpisah", "duration": "0:00"},
    ]
  }
];
